/**
 * 资源导航 demo 种子 —— 15 个链接 / 6 个分类
 *
 * 当用户在 admin 删除全部或导入空 bundle 时作为兜底。
 * 真实部署时建议从 admin 维护，或编辑 seed 文件后 build。
 */
import type { LinkEntry } from './types';

const now = '2025-03-15T00:00:00.000Z';

export const SEED_LINKS: LinkEntry[] = [
  // ============== design ==============
  {
    id: 'lnk_figma',
    name: 'Figma',
    url: 'https://figma.com',
    icon: '🎨',
    description: '浏览器即用的协作设计工具。设计稿、组件库、原型一套搞定。',
    descriptionEn: 'Browser-based collaborative design tool. Design, components, prototypes — all in one.',
    category: 'design',
    tags: ['UI', '原型', '协作'],
    featured: true,
    pricing: 'freemium',
    clicks: 124,
    order: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'lnk_undraw',
    name: 'unDraw',
    url: 'https://undraw.co',
    icon: '🖼',
    description: '免费开源插画库，统一风格，单色可换。写博客 / 做 Landing 必备。',
    category: 'design',
    tags: ['插画', '免费'],
    featured: false,
    pricing: 'free',
    clicks: 56,
    order: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'lnk_remove_bg',
    name: 'remove.bg',
    url: 'https://remove.bg',
    icon: '✂️',
    description: '一键抠图。免费版够用，预览图就够清晰。',
    category: 'design',
    tags: ['图片', 'AI'],
    featured: false,
    pricing: 'freemium',
    clicks: 38,
    order: 3,
    createdAt: now,
    updatedAt: now,
  },

  // ============== dev ==============
  {
    id: 'lnk_vercel',
    name: 'Vercel',
    url: 'https://vercel.com',
    icon: '▲',
    description: '前端部署首选。Git push 自动部署，全球 CDN，Preview 一键生成。',
    descriptionEn: 'Best-in-class frontend deployment. Git push to deploy, global CDN, instant Preview URLs.',
    category: 'dev',
    tags: ['部署', 'CDN', 'Next.js'],
    featured: true,
    pricing: 'freemium',
    clicks: 89,
    order: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'lnk_github',
    name: 'GitHub',
    url: 'https://github.com',
    icon: '🐙',
    description: '代码托管 + Actions + Pages。零成本跑静态站。',
    category: 'dev',
    tags: ['Git', 'CI/CD', 'Pages'],
    featured: false,
    pricing: 'freemium',
    clicks: 215,
    order: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'lnk_mdn',
    name: 'MDN Web Docs',
    url: 'https://developer.mozilla.org',
    icon: '📚',
    description: 'Web 技术最权威文档。每次查 API 必开。',
    category: 'dev',
    tags: ['文档', 'Web'],
    featured: false,
    pricing: 'free',
    clicks: 178,
    order: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'lnk_can_i_use',
    name: 'Can I Use',
    url: 'https://caniuse.com',
    icon: '✅',
    description: '浏览器兼容查询。CSS 新特性 / Web API 必查。',
    category: 'dev',
    tags: ['兼容性', 'Web'],
    featured: false,
    pricing: 'free',
    clicks: 67,
    order: 4,
    createdAt: now,
    updatedAt: now,
  },

  // ============== writing ==============
  {
    id: 'lnk_notion',
    name: 'Notion',
    url: 'https://notion.so',
    icon: '📝',
    description: '一站式的笔记 / 数据库 / 项目管理。写作 + 整理两不误。',
    category: 'writing',
    tags: ['笔记', '协作'],
    featured: false,
    pricing: 'freemium',
    clicks: 145,
    order: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'lnk_obsidian',
    name: 'Obsidian',
    url: 'https://obsidian.md',
    icon: '🪨',
    description: '本地 Markdown 笔记，双向链接。知识管理的瑞士军刀。',
    category: 'writing',
    tags: ['Markdown', '本地'],
    featured: true,
    pricing: 'free',
    clicks: 92,
    order: 2,
    createdAt: now,
    updatedAt: now,
  },

  // ============== marketing ==============
  {
    id: 'lnk_buffer',
    name: 'Buffer',
    url: 'https://buffer.com',
    icon: '📱',
    description: '跨平台社媒排程。一次写，多次发，节省运营时间。',
    category: 'marketing',
    tags: ['社媒', '排程'],
    featured: false,
    pricing: 'freemium',
    clicks: 34,
    order: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'lnk_ahrefs',
    name: 'Ahrefs',
    url: 'https://ahrefs.com',
    icon: '🔍',
    description: 'SEO 工具王者。关键词研究 / 外链分析 / 竞品监控。',
    category: 'marketing',
    tags: ['SEO', '关键词'],
    featured: false,
    pricing: 'paid',
    clicks: 47,
    order: 2,
    createdAt: now,
    updatedAt: now,
  },

  // ============== analytics ==============
  {
    id: 'lnk_plausible',
    name: 'Plausible',
    url: 'https://plausible.io',
    icon: '📈',
    description: '轻量级隐私友好分析。无 Cookie，GDPR 合规，单页脚本 < 1KB。',
    descriptionEn: 'Lightweight privacy-friendly analytics. No cookies, GDPR-compliant, < 1KB script.',
    category: 'analytics',
    tags: ['分析', '隐私'],
    featured: true,
    pricing: 'paid',
    clicks: 78,
    order: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'lnk_umami',
    name: 'Umami',
    url: 'https://umami.is',
    icon: '🟢',
    description: '开源自托管分析。Google Analytics 的现代替代。',
    category: 'analytics',
    tags: ['分析', '自托管', '开源'],
    featured: false,
    pricing: 'free',
    clicks: 56,
    order: 2,
    createdAt: now,
    updatedAt: now,
  },

  // ============== productivity ==============
  {
    id: 'lnk_raycast',
    name: 'Raycast',
    url: 'https://raycast.com',
    icon: '🚀',
    description: 'Mac 上的命令面板 + 应用启动器 + 数百个扩展。',
    category: 'productivity',
    tags: ['Mac', '效率'],
    featured: false,
    pricing: 'freemium',
    clicks: 64,
    order: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'lnk_cron',
    name: 'cron-notion',
    url: 'https://github.com/search?q=cron+notion&type=repositories',
    icon: '⏰',
    description: '把 Notion 当数据库定时同步 / 备份的工具集。',
    category: 'productivity',
    tags: ['自动化', 'Notion'],
    featured: false,
    pricing: 'free',
    clicks: 23,
    order: 2,
    createdAt: now,
    updatedAt: now,
  },
];
