/**
 * 4 套主题预设
 * 每套都完整定义所有 CSS 变量 + 预览色卡
 */
import type { Theme, ThemeMode } from '../types';

const sharedRadii = {
  '--radius-sm': '4px',
  '--radius-md': '8px',
  '--radius-lg': '12px',
};

export const THEME_PRESETS: Record<ThemeMode, Theme> = {
  light: {
    id: 'light',
    name: '明亮',
    description: '清新通透的默认主题，适合日间写作与阅读。',
    variables: {
      '--color-bg': '#ffffff',
      '--color-bg-elevated': '#fafafa',
      '--color-bg-subtle': '#f4f4f5',
      '--color-fg': '#0a0a0a',
      '--color-fg-muted': '#52525b',
      '--color-fg-subtle': '#a1a1aa',
      '--color-primary': '#6366f1',
      '--color-primary-fg': '#ffffff',
      '--color-secondary': '#f4f4f5',
      '--color-secondary-fg': '#18181b',
      '--color-accent': '#a855f7',
      '--color-accent-fg': '#ffffff',
      '--color-border': '#e4e4e7',
      '--color-muted': '#f4f4f5',
      '--color-success': '#10b981',
      '--color-warning': '#f59e0b',
      '--color-danger': '#ef4444',
      '--color-code-bg': '#f4f4f5',
      '--color-code-fg': '#18181b',
      '--color-ring': '#6366f1',
      ...sharedRadii,
    },
    preview: {
      bg: '#ffffff',
      fg: '#0a0a0a',
      primary: '#6366f1',
      accent: '#a855f7',
    },
  },
  dark: {
    id: 'dark',
    name: '暗夜',
    description: '深色背景 + 冷色调高对比，夜间阅读首选。',
    variables: {
      '--color-bg': '#09090b',
      '--color-bg-elevated': '#18181b',
      '--color-bg-subtle': '#27272a',
      '--color-fg': '#fafafa',
      '--color-fg-muted': '#a1a1aa',
      '--color-fg-subtle': '#71717a',
      '--color-primary': '#818cf8',
      '--color-primary-fg': '#09090b',
      '--color-secondary': '#27272a',
      '--color-secondary-fg': '#fafafa',
      '--color-accent': '#c084fc',
      '--color-accent-fg': '#09090b',
      '--color-border': '#27272a',
      '--color-muted': '#27272a',
      '--color-success': '#34d399',
      '--color-warning': '#fbbf24',
      '--color-danger': '#f87171',
      '--color-code-bg': '#18181b',
      '--color-code-fg': '#fafafa',
      '--color-ring': '#818cf8',
      ...sharedRadii,
    },
    preview: {
      bg: '#09090b',
      fg: '#fafafa',
      primary: '#818cf8',
      accent: '#c084fc',
    },
  },
  sepia: {
    id: 'sepia',
    name: '护眼',
    description: '米黄底色 + 棕色字体，长时间阅读不易疲劳。',
    variables: {
      '--color-bg': '#f5ecd9',
      '--color-bg-elevated': '#ede1c6',
      '--color-bg-subtle': '#e3d4b3',
      '--color-fg': '#3b2e1f',
      '--color-fg-muted': '#6b5736',
      '--color-fg-subtle': '#a08d62',
      '--color-primary': '#a0522d',
      '--color-primary-fg': '#fbf6e7',
      '--color-secondary': '#e3d4b3',
      '--color-secondary-fg': '#3b2e1f',
      '--color-accent': '#8b6914',
      '--color-accent-fg': '#fbf6e7',
      '--color-border': '#d6c39e',
      '--color-muted': '#e3d4b3',
      '--color-success': '#5b7c3a',
      '--color-warning': '#c2871a',
      '--color-danger': '#a84032',
      '--color-code-bg': '#ede1c6',
      '--color-code-fg': '#3b2e1f',
      '--color-ring': '#a0522d',
      ...sharedRadii,
    },
    preview: {
      bg: '#f5ecd9',
      fg: '#3b2e1f',
      primary: '#a0522d',
      accent: '#8b6914',
    },
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: '赛博朋克',
    description: '霓虹荧光色 + 黑色背景，浓郁的赛博朋克氛围。',
    variables: {
      '--color-bg': '#0a0014',
      '--color-bg-elevated': '#150025',
      '--color-bg-subtle': '#1f0036',
      '--color-fg': '#f9f5ff',
      '--color-fg-muted': '#c084fc',
      '--color-fg-subtle': '#7c3aed',
      '--color-primary': '#00f5ff',
      '--color-primary-fg': '#0a0014',
      '--color-secondary': '#1f0036',
      '--color-secondary-fg': '#f9f5ff',
      '--color-accent': '#ff00d4',
      '--color-accent-fg': '#0a0014',
      '--color-border': '#7c3aed',
      '--color-muted': '#1f0036',
      '--color-success': '#39ff14',
      '--color-warning': '#fff700',
      '--color-danger': '#ff073a',
      '--color-code-bg': '#150025',
      '--color-code-fg': '#00f5ff',
      '--color-ring': '#00f5ff',
      ...sharedRadii,
    },
    preview: {
      bg: '#0a0014',
      fg: '#f9f5ff',
      primary: '#00f5ff',
      accent: '#ff00d4',
    },
  },
};

export const THEME_LIST: Theme[] = [
  THEME_PRESETS.light,
  THEME_PRESETS.dark,
  THEME_PRESETS.sepia,
  THEME_PRESETS.cyberpunk,
];